# Netlify Configuration for Full Stack App
# This deploys both the Vue.js frontend and Node.js backend

# Build settings
[build]
  # Build command - only build client (server runs as serverless function)
  command = "npm run build:netlify"
  
  # The directory to publish (client build output)
  publish = "client/dist"
  
  # Functions directory for serverless functions (backend)
  functions = "netlify/functions"

# Function bundling configuration
[functions]
  # Include server dist folder in function bundle
  included_files = ["server/dist/**"]
  # Use esbuild for faster bundling
  node_bundler = "esbuild"

# Environment variables (set these in Netlify UI)
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_PRODUCTION = "false"

# Automatically install function dependencies
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Redirect API calls to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api/health"
  status = 200

# SPA fallback - redirect all other routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Dev server settings (for local development with Netlify CLI)
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3001
  publish = "client/dist"
  autoLaunch = true

