# Netlify Configuration for Client-Only Deployment

[build]
  # Base directory - where Netlify should run commands
  base = "client"
  
  # Build command - build the Vue.js app
  command = "npm install && npm run build"
  
  # Publish directory - where the built files are
  publish = "dist"

# Node version
[build.environment]
  NODE_VERSION = "18"

# SPA redirect - all routes go to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

